name: fitbody_admin
description: "FitBody — приложение АДМИНА (Flutter + Firebase, вход через Google)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_sign_in: ^7.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
